require('plugin-options/general')
require('plugin-options/fzf')
require('plugin-options/gitsigns')
require('plugin-options/nvim-treesitter')
require('plugin-options/cmp')
require('plugin-options/obsidian')
