[Service]
CapabilityBoundingSet=CAP_DAC_READ_SEARCH
AmbientCapabilities=CAP_DAC_READ_SEARCH
ExecStart=
ExecStart=/usr/bin/restic backup $BACKUP_PATHS --retry-lock=1h --tag %i --exclude-caches --limit-upload $LIMIT_UPLOAD --exclude-file=/etc/restic/excludes.txt
