require('plugin-options.general')
require('plugin-options.fzf')
require('plugin-options.gitsigns')
require('plugin-options.nvim-treesitter')
require('plugin-options.cmp')
require('plugin-options.obsidian')
require('plugin-options.onedrive')
require('plugin-options.avante')
require('plugin-options.zshbookmarks')
require('plugin-options.mermaid-export')
require('plugin-options.md-to-pdf')
require('plugin-options.nvim-macros')
require('plugin-options.rest-nvim')
require('plugin-options.render-markdown')
-- require('plugin-options.nvim-tree')
